import "tailwindcss/tailwind.css";
import Head from "next/head";
import type { AppProps } from "next/app";
import React from "react";
import Layout from "../components/layout";


function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Sidetrade Next Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>

      <Layout>

        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp;
