import classNames from "classnames";
import Head from "next/head";
import Image from "next/image";
import Product from "../components/product";

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col justify-center items-center">
      <Head>
        <title>Sidetrade Next Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>

      <header className="h-16 px-8 bg-blue-600 text-white w-full text-center sticky top-0 flex items-center justify-center">
	<span>HEADER</span>

  <div className="h-10 w-10 bg-white rounded-full flex items-center justify-center text-blue-600 ">
  <span className="material-icons items-center">face</span>
</div>
 </header>

      <main className="py-20 flex flex-col flex-1 justify-center items-center">
        <h1 className="m-0 leading-snug text-6xl text-center">
          Welcome to{" "}
          <a
            className="text-blue-600 no-underline hover:underline focus:underline"
            href="https://nextjs.org"
          >
            Next.js!
          </a>
        </h1>

        <p className="leading-normal text-2xl text-center">
          Get started by editing{" "}
          <code className="bg-gray-100 rounded-md p-3 text-lg font-mono">
            pages/index.js
          </code>
        </p>

<div className="mt-10 flex flex-wrap flex-col sm:flex-row w-full sm:max-w-3xl justify-center items-center">

<Product name="T-shirt" />
<Product name="Vest" />
<Product name="Hoodie" />
<Product name="Shorts" />
<Product name="Shirt" />
<Product name="Trousers" />

</div>

      </main>

      <footer className="w-full h-24 flex justify-center items-center border-t border-solid border-gray-200">
        <a
          className="flex flex-1 justify-center items-center"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
